### ISSUE TITLE
grive2 does not compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by SamoPP** [vitalif/grive2#114]
Hi,

I followed the install/compile instruction and I get this errors:

[ 98%] Linking CXX executable grive
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libgcrypt.so: undefined reference to `gpg_strsource@GPG_ERROR_1.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libgcrypt.so: undefined reference to `gpg_err_code_from_syserror@GPG_ERROR_1.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libgcrypt.so: undefined reference to `gpg_err_set_errno@GPG_ERROR_1.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libgcrypt.so: undefined reference to `gpg_strerror@GPG_ERROR_1.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libgcrypt.so: undefined reference to `gpg_err_code_from_errno@GPG_ERROR_1.0'
collect2: error: ld returned 1 exit status
grive/CMakeFiles/grive_executable.dir/build.make:106: recipe for target 'grive/grive' failed
make[2]: *** [grive/grive] Error 1
CMakeFiles/Makefile2:218: recipe for target 'grive/CMakeFiles/grive_executable.dir/all' failed
make[1]: *** [grive/CMakeFiles/grive_executable.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
[100%] Linking CXX executable unittest
/usr/bin/cmake: /usr/local/lib/libcurl.so.4: no version information available (required by /usr/bin/cmake)
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libgcrypt.so: undefined reference to `gpg_err_set_errno@GPG_ERROR_1.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libgcrypt.so: undefined reference to `gpg_err_code_from_syserror@GPG_ERROR_1.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libgcrypt.so: undefined reference to `gpg_err_code_from_errno@GPG_ERROR_1.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libgcrypt.so: undefined reference to `gpg_strerror@GPG_ERROR_1.0'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libgcrypt.so: undefined reference to `gpg_strsource@GPG_ERROR_1.0'
collect2: error: ld returned 1 exit status
libgrive/CMakeFiles/unittest.dir/build.make:293: recipe for target 'libgrive/unittest' failed
make[2]: *** [libgrive/unittest] Error 1
CMakeFiles/Makefile2:163: recipe for target 'libgrive/CMakeFiles/unittest.dir/all' failed
make[1]: *** [libgrive/CMakeFiles/unittest.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by n1try** [comment]
+1

**Comment by Alexmp4** [comment]
+1

**Comment by Slaedr** [comment]
I'm using grive2 in Ubuntu 16.04 and I did not get this error. Make sure you use the latest files from this repo, I had once downloaded an older version by mistake and it did not compile.

**Comment by isgroup-srl** [comment]
As @Slaedr no error here, Ubuntu 16.04.

**Comment by poligarcia** [comment]
I had this same issue on the same environ and fixed it by checking out ae06eccb38b2fe250c9ddeac3e3973f80b8a0aa9, deleting the build dir and exactly following the build instructions.

**Comment by gaobb** [comment]
+1
